### ISSUE TITLE
The directions are to confusing

### ISSUE THREAD

**Issue by TeamHarrisCali** [Robz8/SRLoader#10]
So when i extracted the first link to the SD card, and i read the directions, I couldn't do it. If you can help me step by step that would be great!

and also where can i find sdmc:/roms/nds/ when i extracted it, the SD card is (J:)
![image](https://user-images.githubusercontent.com/34009957/33243943-87c05558-d2a3-11e7-87c2-4d6a6195daad.png)

**Comment by Robz8** [comment]
Move the files out of the SRLoader folder to root.

**Comment by TeamHarrisCali** [comment]
SO leave everything els?

**Comment by TeamHarrisCali** [comment]
I am so sorry Im just new to this sort of thing

**Comment by Robz8** [comment]
Yes, then just launch.

**Comment by TeamHarrisCali** [comment]
ok then, should it show a "game?"

**Comment by TeamHarrisCali** [comment]
because when i go to storage management it does not show anything. does the SD card size matter?

**Comment by Robz8** [comment]
No.
It's because you're not running SRLoader.
Do you have Flipnote installed?

**Comment by TeamHarrisCali** [comment]
no i do not. i was gonna look in the DSI store but it was closed

**Comment by TeamHarrisCali** [comment]
and is there any way for me to get flip note back?

**Comment by TeamHarrisCali** [comment]
I tried factory resting it but it did not come back. flip note came pre-installed when i got it

**Comment by Robz8** [comment]
Sorry, unless you plan on getting a hardmod, you're out of luck. :(
If you have a 3DS with CFW, you can try TWLoader.
