### ISSUE TITLE
Red screen

### ISSUE THREAD

**Issue by Caboosium** [Robz8/SRLoader#11]
When ever I launch a game it loads and then shows a red screen with little white dots (top or bottom screen depends on game) and a white screen. I don't hear any sound during this stage. I did notice the WiFi LED turns off and never turns back on.

In the meantime I'll continue to mess with settings and try to figure it out. 

Console: DSi

SD:\_nds\nds-bootstrap.ini
`[NDS-BOOTSTRAP]`
`NDS_PATH = sd:/roms/nds/Pokemon - HeartGold Version (US).nds`
`SAV_PATH = sd:/roms/nds/Pokemon - HeartGold Version (US).sav`
`ARM7_DONOR_PATH = sd:/roms/nds/donor.nds`
`USE_ARM7_DONOR = 1`
`DONOR_SDK_VER = 0`
`CHECK_COMPATIBILITY = 1`
`BOOTSTRAP_PATH = sd:/_nds/dsiware-bootstrap.nds`
`ROMREAD_LED = 1`
`BOOST_CPU = 1`
`BOOST_VRAM = 1`
`BOOTSPLASH = 1`
`DEBUG = 1`
`RESETSLOT1 = 0`
`LOCK_ARM9_SCFG_EXT = 0`
`PATCH_MPU_REGION = 0`
`PATCH_MPU_SIZE = 0`
`NTR_TOUCH = 1`

**Comment by Robz8** [comment]
Looks like you didn't set Mario Kart DS as donor ROM.
To set MKDS as donor ROM, press SELECT on it in SRLoader.

**Comment by Caboosium** [comment]
Still happening

**Comment by Caboosium** [comment]
I'm using the Zelda 4 Swords save hack thing if thats important.

**Comment by Robz8** [comment]
See if this fixes the issue: https://gbatemp.net/threads/release-easy-sudoku-sudokuhax-installer.488899/

**Comment by Caboosium** [comment]
Ok give me a moment...

**Comment by Caboosium** [comment]
Sudoku worked

**Comment by Robz8** [comment]
So is the issue fixed?

**Comment by Caboosium** [comment]
Yes

**Comment by Caboosium** [comment]
You should probably add a wiki to this project to store fixes for stupid issues.
