### ISSUE TITLE
[Not A Problem] GBA games idea

### ISSUE THREAD

**Issue by Caboosium** [Robz8/SRLoader#12]
The DS Lite had the ability to run GBA games from a cart and I was wondering if part of the DS lite system software could be used to run .gba games on the DSi at full/near cart speed.

Note: Could not find a PM/Message button on your profile page. Maybe Github does not have this feature.

**Comment by Robz8** [comment]
There's GBARunner2, which can run most (or some?) games as full speed.
You'll either need a flashcard or RocketLauncher (not released yet) to use GBARunner2.
