### ISSUE TITLE
Please help with Pókemon Black

### ISSUE THREAD

**Issue by blackkawa** [Robz8/SRLoader#14]
I am trying to run pókemon black, on my ace3ds on my dsi 1.4.5, but i receive the message: Start failed. Error 1. Can i know the reason behind the error and how to repair it?

**Comment by Robz8** [comment]
Make sure you have the whole "_nds" folder from the SRLoader 7z file extracted to the SD card.
Also, Pokemon BW isn't compatible for DSiWarehax users.
