### ISSUE TITLE
saves are not loading from the .sav file (pokémon series)

### ISSUE THREAD

**Issue by BluRosie** [Robz8/SRLoader#15]
whenever a game from the main series pokémon ones (not including gen 5) is loaded with a preexisting save, an error comes up and renders the game unplayable, as it would restart to the title when a is pressed:

mindcrystal, a french soulsilver hack:
"Erreur de communication.
Vous allez être renvoyé à l'écran titre.  Veuillez appuyer sur le bouton A."
platinum and diamond:
"A communication error has occurred.
If you were in the Union Room, you will be returned there.  In all other cases, you will be returned to wherever you last saved.  Please press the A Button."

however, it works perfectly fine with other games, specifically super mario 64 ds and new super mario bros.

note that i'm on dsiwarehax, specifically using sudokuhax to load into srloader.
said saves work perfectly fine if loaded through a 2ds running luma with twloader as well, which is what is lead me here
any help or suggestions would be appreciated~

EDIT:  the error specifically comes up directly after making it past the title screen, if that helps

**Comment by Robz8** [comment]
You'll have to wait for proper save patching for SDK3-4 games, without the need for a donor ROM.

**Comment by BluRosie** [comment]
thanks so much for the quick reply~
real quick, though
donor rom or donor cartridge?  if the problem is simply the lack of a donor rom, which would i be using over mkds?

**Comment by Robz8** [comment]
You won't be using a donor at all.

**Comment by BluRosie** [comment]
ah, ok.  thanks for answering, and good luck in future endeavors!  your work is well-appreciated.
