### ISSUE TITLE
Bottom Screen blacks out when sometimes entering SRLoader

### ISSUE THREAD

**Issue by ChampionLeake** [Robz8/SRLoader#17]
Sometimes when opening SRLoader v3 (via sudokuhax) the bottom screen will turn black but the top screen is normal.

**Comment by Robz8** [comment]
The text can still be seen on the bottom screen, though.

**Comment by ChampionLeake** [comment]
I noticed sometimes on boot, screens will go black and freeze the console as well. Sometimes when selecting a game or going to settings.

**Comment by Robz8** [comment]
Since this doesn't seem to be happening on later versions, this can be closed.
