### ISSUE TITLE
[Request] Instructions to use on DS/Lite

### ISSUE THREAD

**Issue by Dimensional** [Robz8/SRLoader#23]
Can you include instructions for those who want to use this properly on their DS/lite? I've been at this over an hour using the files provided for my Acekard 2i and Gateway Blue Card, and I can't get the menu or gbarunner to work. They just crash on me every time I load. I don't know what I'm doing wrong, and I'm following to the best that I can what to do. Just copy the files for the Flash cart to it's storage, and load on DS.

**Comment by Robz8** [comment]
Did you set the flashcard in SRLoader settings screen?

**Comment by Dimensional** [comment]
SRLoader won't load on my Gateway Blue Card in my DSlite. That's the primary card I'm trying to get it to work on. My AK2i was just because I was bored. But the Gateway card won't load when starting it on my DSlite. I have to use the GW official loader, and I don't even know how you got SRLoader to auto-boot in the video.

**Comment by Robz8** [comment]
The R4 card I'm using in the video is the kind of flashcard that autoboots, even if the system is not set to autostart the inserted card.
Also, there's no autoboot file for GW blue card.

**Comment by Dimensional** [comment]
Okay. But are there any instructions for properly setting up each card, besides just copying files onto the flash cart storage? The provided storage for things like flash carts don't have the SRLoader or gbarunner part of them. I thought, based on the video with the DSlite, I just copy gbarunner_fc to my flashcart and load from there, but it doesn't seem to be working. I then copied boot_fc, but that doesn't work. Best thing I get when using all the files is a white top screen and a black R4 menu screen that has no text, just an SD icon, GBA icon, and folder. Selecting an icon causes an empty popup to appear. Screenshot provided.

![20180226_220855 1](https://user-images.githubusercontent.com/5027297/36710188-f4dcf9de-1b41-11e8-8410-dd6de1d335bc.jpg)

Replacing your version of _DSMENU.DAT with the GW provided version loads a proper menu screen, but when attempting to load SRLoader.nds from the flashcart, it displays the message "Start failed. Error 1" on the bottom screen with a black background while top screen is all white.

**Comment by Robz8** [comment]
> but when attempting to load boot_fc.nds from the flashcart, it displays the message "Start failed. Error 1" on the bottom screen with a black background while top screen is all white.

To fix that error, put the `_nds` folder from `SRLoader.7z` into the flashcard SD root.
Error 1 means that the file that's trying to be booted, isn't found.

**Comment by Robz8** [comment]
Also, there's already instructions at the [GBATemp thread](https://gbatemp.net/threads/srloader-gui-for-flashcards-also-a-nds-app-for-dsi.472200/) (see Instructions (Flashcard users)).
