### ISSUE TITLE
[Feature Request] Add an option in which we can define where the saves are

### ISSUE THREAD

**Issue by WodsonKun** [Robz8/SRLoader#28]
Makes it easy to manage files and saves
Ex:
Games = ROMS/NDS
Saves = ROMS/SAV

**Comment by Multimegamander** [comment]
that makes sense, and hey Wodson 👋

**Comment by Robz8** [comment]
Flashcard ROM loaders only use the save file if it's in the same location as the ROM folder, and has the same filename as the ROM (but with .sav instead of .nds).
