### ISSUE TITLE
every release past 3.3.0 whitescreen error

### ISSUE THREAD

**Issue by coolhaus** [Robz8/SRLoader#30]
First of all great job on this frontend for nds-bootstrap it works amazing. However after multiple tests I've confirmed (atleast for me) that every SRLoader release after 3.3.0 gives me a white screen when I try to load common roms. The latest release however does manage to boot Mario 64 DS and Mario Kart DS. When I use SR Loader 3.3.0 every rom that is in the compatability list works fine.

**Comment by Robz8** [comment]
The current version has a bug relating to setting a donor ROM. Next version will fix that bug.
As a workaround, change `sd:/` to `/` in `sd:/_nds/srloader/settings.ini`, then set MKDS as donor ROM again.

**Comment by Robz8** [comment]
SRLoader v3.4.2 should fix the issue now.
