### ISSUE TITLE
Not an issue, but damn, it's nice to finally be able to install this as a .tia, now that Hiya and unlauncher is out

### ISSUE THREAD

**Issue by Multimegamander** [Robz8/SRLoader#35]

**Comment by qgerman2** [comment]
what are the benefits of installing as a .tia compared to just running it from sudokuhax?

**Comment by Robz8** [comment]
Sound is fixed on all DS games, including ones with thumb card reads.
You can also use a donor cart for saving in SDK5 games, and can also be able to play DSi-enhanced games (in NTR mode, though).
