### ISSUE TITLE
White screen when loading .NDS Rom, HELP

### ISSUE THREAD

**Issue by FROEZOEN** [Robz8/SRLoader#36]
After 12 hours of installing this tool I finally got it, works flawlessy except for launching NDS back ups, 
It goes to the loading screen, freezers for a moment, then goes to a white screen. Ive tried 3 games.

New Super Mario Bros.

Mario & Luigi : Partners in Time

Mario & Luigi : Bowsers Inside Story

Please help I've been at this for ages.

**Comment by Robz8** [comment]
Try formatting your SD card to FAT32 with 32kb cluster size.
