### ISSUE TITLE
Optional BUT POSSABLE n64 emu for 3ds to be compiled if fixed up

### ISSUE THREAD

**Issue by mjpitsicalis2** [Robz8/SRLoader#39]
i saw this https://github.com/SNGames-Gaming/3D64 and think if we can fix it up and compile it maby we can see  what the 3ds can do with n64 games as a test, and if somehow its good we can add it into twloader, sorry but just wanted to say that. Hope we can work on it

**Comment by Robz8** [comment]
You posted in the SRLoader, and you suggested a feature for TWLoader.
SRLoader and TWLoader is for NTR/TWL-mode stuff only.
