### ISSUE TITLE
Very slow, even freezing experience with loading .NDS files

### ISSUE THREAD

**Issue by ItsDaFaz** [Robz8/SRLoader#42]
I haven't tried any other files but when it comes with .nds files like Sonic Colors the game shows up but for every second of activity it freezes for 30 seconds or so. I am running Hiya CFW on a 2GB FAT32 Partitioned SD Card (with remaining 6GB unallocated). Please tell me what to do to make it bearable.

**Comment by Robz8** [comment]
Does your SD card have 32kb cluster size?

**Comment by ItsDaFaz** [comment]
I don't really know, could you tell me how to do it?

**Comment by Robz8** [comment]
Use SDFormatter 4.0 to format your SD card.

**Comment by ItsDaFaz** [comment]
This has SUBSTANTIALLY improved the performance, thank you! The gameplay is very smooth. However it's very slow to load other activities, for example, when loading a cutscene or a menu.

**Comment by Robz8** [comment]
Yeah, that's normal for now. It may improve in the future.
