### ISSUE TITLE
White Screen when trying to load SRLoader 

### ISSUE THREAD

**Issue by DarkGabbz** [Robz8/SRLoader#5]
https://www.youtube.com/watch?v=4HFBr8gYt5I

**Comment by Robz8** [comment]
Did you extract everything to the SD root?
If so try holding START while SRLoader starts.

**Comment by Robz8** [comment]
If that didn't work, you may have to use SRLoader as BOOT.NDS, and put hbmenu in "sd:/roms/nds/".

**Comment by Robz8** [comment]
If you fixed the issue, you can close it. :)
