### ISSUE TITLE
`Guru Meditation Error!` Failure to get to menu

### ISSUE THREAD

**Issue by DeathCamel57** [Robz8/SRLoader#9]
I'm using Sodukuhax.
I've typed up the error for the developer's convenience.

`Guru Meditation Error!`
`Data abort!`
`PC: 02004426 r8 : 00000001`
`r1: F97C0000 r9 : 00000000`
`r2: 00000000 r10: 86848000`
`r3: 00000000 r11: 00005940`
`r4: 00000000 r12: 06840003`
`r5: 0B002ABC sp : 0B002A80`
`r6: 0B002B08 lr : 02004387`
`r7: 00000001 pc : 0200442E`
`0B002A80: 00000001 0B003B50`
`0B002A88: 00000001 0204FE48`
`0B002A90: 00000001 0B002ABC`
`0B002A98: 00000000 0204F774`
`0B002AA0: 00000000 0200459D`
`0B002AA8: 00000001 00000000`
`0B002AB0: 0B002ABC 00000001`
`0B002AB8: 000635FF 0B002B08`
`0B002AC0: 44535F69 00032E48`
`0B002AC8: 000081B6 00010001`

![hni_0002](https://user-images.githubusercontent.com/1226646/30779284-93110a58-a0ba-11e7-8d14-a08fbaa40812.JPG)
![hni_0001](https://user-images.githubusercontent.com/1226646/30779285-93119f36-a0ba-11e7-842e-4fe6138ee9dc.JPG)

**Comment by Robz8** [comment]
Does it happen every time?

**Comment by DeathCamel57** [comment]
It happens about 50% of the time. 
If you have a debug version, I can build it from source, and get some logs.

**Comment by DeathCamel57** [comment]
Also, when it does start, the first game looks correct. However, any game other than the first has an artifact on the name section.

![hni_0004](https://user-images.githubusercontent.com/1226646/30779355-2e0e3e4e-a0bc-11e7-88e2-ff618d799e2e.JPG)
![hni_0003](https://user-images.githubusercontent.com/1226646/30779356-2e1d2774-a0bc-11e7-9e0d-22187aecc303.JPG)

**Comment by Robz8** [comment]
That artifact is due to it not reading the "é" character correctly.

**Comment by Robz8** [comment]
As for the `Guru Meditation Error!` error, I probably can't fix that.
